server:
  port: 8081

application:
  version: 1.0.1-SNAPSHOT

spring:
  # ========= DATABASE MYSQL =========== #
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user_library
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

