app:
  lesson: LESSON 1

lesson:
  author: alessandro.vizzarro@aesys.tech
  welcome-message: Welcome to ${app.lesson}

dgreg:
  config:
    appName: Lessone One Print Info
    version: 1.0.0
    description: Endpoint printing info.


