app:
  lesson: LESSON 1

lesson:
  author: matteo.fornaro@aesys.tech
  welcome-message: Welcome to ${app.lesson} !!!

fornaro:
  config:
    appName: Lesson One Print Info
    version: 1.0.0
    description: Endpoint printing info



dicesare:
  config:
    appName: Lesson one Print info
    version: 1.0.0
    description: Endpoint printing info.
