app:
  lesson: LESSON 1

lesson:
  author: caterina.derosa@aesys.tech
  welcome-message: Welcome to ${app.lesson}

caterina:
 config:
  appName: Lesson One Print Info
  version: 1.0.0
  description: Endpoint printing info

