vizzarro:
    config:
        version: 1.0.1
<<<<<<< HEAD

seccia:
    config:
        description: Endpoint made by Seccia
        version: 1.0.3-SNAPSHOT
=======
        appName: Devel Environment lesson

vervenna:
    config:
        version: 1.0.1
        appName: Devel Environment lesson by Vervenna
brandolini:
    config:
        description: This is developement
>>>>>>> e8e0d8377a7a7e4f8cd614be68e029801ac5a513
