app:
  lesson: LESSON 1

lesson:
  author: matteo.fornaro@aesys.tech
  welcome-message: Welcome to ${app.lesson} !!!

<<<<<<< HEAD
<<<<<<< HEAD
dilorito:
  config:
    appName: Lesson One Print Info
    version: 1.0.0
    description: Endpoint printing info.

=======
<<<<<<< HEAD
seccia:
=======
fornaro:
>>>>>>> 613d12fb56ee3d1fa01b5bbfb210316bd5b2bd99
  config:
    appName: Lesson One Print Info
    version: 1.0.0
    description: Endpoint printing info



<<<<<<< HEAD
>>>>>>> efa541dee4c82ed44a30925138138856031e809a
>>>>>>> bc2fbdcd5dd68432f135f7233a51241fab65fe44
=======
>>>>>>> 613d12fb56ee3d1fa01b5bbfb210316bd5b2bd99
