app:
  lesson: LESSON 1

lesson:
  author: alessandro.vizzarro@aesys.tech
  welcome-message: Welcome to ${app.lesson}

maiolini:
  config:
    version: 1.0.0
    appName: Lesson One Print
    description: Endpoint printing info Valerio Maiolini

