<<<<<<< HEAD
dirocco:
=======
server:
    port: 8081
    error:
        whitelabel:
            enabled: false

vizzarro:
>>>>>>> bd44ebd6d8e17a7cfa070e62e7e266a23d5cfc09
    config:
        version: 1.0.1
<<<<<<< HEAD
=======

vervenna:
    config:
        version: 1.0.1
        appName: Production Environment lesson by Vervenna

brandolini:
    config:
        description: This is production
>>>>>>> e8e0d8377a7a7e4f8cd614be68e029801ac5a513
