dirocco:
    config:
        version: 1.0.1
<<<<<<< HEAD
=======
        appName: Devel Environment lesson

vervenna:
    config:
        version: 1.0.1
        appName: Devel Environment lesson by Vervenna
brandolini:
    config:
        description: This is developement
>>>>>>> e8e0d8377a7a7e4f8cd614be68e029801ac5a513
